# Generated by Django 5.1.3 on 2024-11-26 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_listitem_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
